package unit;

import com.example.model.Cliente;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import util.TestDataFactory;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for User model class.
 * Demonstrates comprehensive testing of a domain model with Lombok annotations.
 * 
 * Testing Strategy:
 * - Constructor behavior and initialization
 * - Getter/Setter functionality (auto-generated by Lombok)
 * - Business logic methods (custom methods)
 * - Object contract methods (equals, hashCode, toString - generated by Lombok)
 * - Edge cases and validation
 * 
 * Test Organization:
 * - Uses @Nested classes to group related tests logically
 * - Each nested class focuses on a specific aspect of the User class
 * - @DisplayName provides clear descriptions of what each test verifies
 * - @ParameterizedTest for testing multiple input scenarios
 */
@DisplayName("User Model Unit Tests")
class UserUnitTest {

  private Cliente user;

  @BeforeEach
  void setUp() {
    // Arrange: Create a fresh User instance for each test to ensure isolation
    user = TestDataFactory.createBasicUser();
  }

  @AfterEach
  void tearDown() {
    // Clean up after each test to prevent memory leaks in large test suites
    user = null;
  }

  @Nested
  @DisplayName("Constructor Tests")
  class ConstructorTests {
    /**
     * Tests verify that User constructors work correctly and initialize fields
     * properly.
     * These tests ensure that Lombok's @NoArgsConstructor and custom constructors
     * behave as expected, including proper default value assignment.
     */

    @Test
    @DisplayName("Should create user with default constructor and set default values")
    void shouldCreateUserWithDefaultConstructor() {
      // Act: Create a User using the default constructor (generated by Lombok
      // @NoArgsConstructor)
      Cliente newUser = new Cliente();

      // Assert: Verify that default values are properly set
      // - id, username, email should be null (no default values)
      // - createdAt should be automatically set to current time
      // - active should default to true as specified by @Builder.Default
      assertThat(newUser.getId()).isNull();
      assertThat(newUser.getUsername()).isNull();
      assertThat(newUser.getEmail()).isNull();
      assertThat(newUser.getCreatedAt()).isNotNull();
      assertThat(newUser.isActive()).isTrue();
    }

    @Test
    @DisplayName("Should create user with username and email using convenience constructor")
    void shouldCreateUserWithUsernameAndEmail() {
      // Arrange: Prepare test data
      String username = "john_doe";
      String email = "john@example.com";

      // Act: Create User using the custom convenience constructor
      Cliente newUser = new Cliente(username, email);

      // Assert: Verify that the constructor properly initializes all fields
      // - username and email should be set to provided values
      // - id should remain null (not provided)
      // - createdAt should be automatically set
      // - active should default to true
      assertThat(newUser.getUsername()).isEqualTo(username);
      assertThat(newUser.getEmail()).isEqualTo(email);
      assertThat(newUser.getId()).isNull();
      assertThat(newUser.getCreatedAt()).isNotNull();
      assertThat(newUser.isActive()).isTrue();
    }

    @Test
    @DisplayName("Should create user with id, username and email using full constructor")
    void shouldCreateUserWithIdUsernameAndEmail() {
      // Arrange: Prepare test data including an ID
      Long id = 1L;
      String username = "jane_doe";
      String email = "jane@example.com";

      // Act: Create User using the custom constructor with all main fields
      Cliente newUser = new Cliente(id, username, email);

      // Assert: Verify that all provided fields are properly set
      // This tests the constructor that accepts id, username, and email
      assertThat(newUser.getId()).isEqualTo(id);
      assertThat(newUser.getUsername()).isEqualTo(username);
      assertThat(newUser.getEmail()).isEqualTo(email);
      assertThat(newUser.getCreatedAt()).isNotNull();
      assertThat(newUser.isActive()).isTrue();
    }

    @Test
    @DisplayName("Should create user with ID")
    void shouldCreateUserWithId() {
      Long id = 1L;
      String username = "jane_doe";
      String email = "jane@example.com";

      Cliente newUser = new Cliente(username, email);
      newUser.setId(id);

      assertThat(newUser.getId()).isEqualTo(id);
      assertThat(newUser.getUsername()).isEqualTo(username);
      assertThat(newUser.getEmail()).isEqualTo(email);
    }
  }

  @Nested
  @DisplayName("Business Logic Tests")
  class BusinessLogicTests {

    @Test
    @DisplayName("Should activate user successfully")
    void shouldActivateUser() {
      /*
       * EXPLICACIÓN DE ESTA PRUEBA:
       * ===========================
       * 
       * ¿Qué está probando esta prueba?
       * Esta prueba verifica que el método de negocio activate() funciona
       * correctamente.
       * Prueba el flujo completo: desactivar usuario → activar usuario → verificar
       * estado.
       * 
       * ¿Por qué es importante?
       * - activate() es lógica de negocio crítica para el sistema de usuarios
       * - Los usuarios deben poder ser reactivados después de ser desactivados
       * - Es una operación administrativa común en aplicaciones reales
       * 
       * Patrón de Testing:
       * - Arrange: Desactivamos el usuario para tener un estado inicial conocido
       * - Act: Llamamos activate() para cambiar el estado
       * - Assert: Verificamos que el usuario esté activo
       */

      // Arrange: Deactivate the user first to ensure a known starting state
      user.deactivate();
      assertThat(user.isActive()).isFalse();

      // Act: Activate the user using business logic method
      user.activate();

      // Assert: Verify the user is now active
      assertThat(user.isActive()).isTrue();
    }

    @Test
    @DisplayName("Should deactivate user successfully")
    void shouldDeactivateUser() {
      assertThat(user.isActive()).isTrue();

      user.deactivate();
      assertThat(user.isActive()).isFalse();
    }

    @ParameterizedTest
    @DisplayName("Should validate valid emails")
    @ValueSource(strings = {
        "test@example.com",
        "user.name@domain.co.uk",
        "user+tag@example.org",
        "123@test.com"
    })
    void shouldValidateValidEmails(String validEmail) {
      /*
       * EXPLICACIÓN DE ESTA PRUEBA PARAMETRIZADA:
       * =========================================
       * 
       * ¿Qué es una prueba parametrizada?
       * Las pruebas parametrizadas ejecutan el mismo test múltiples veces con
       * diferentes valores de entrada. Esto es ideal para probar validaciones.
       * 
       * ¿Por qué es importante?
       * - Permite probar múltiples casos con una sola definición de test
       * - Aumenta la cobertura de testing con menos código
       * - JUnit 5 ejecuta cada valor como un test separado
       * - Muy útil para validaciones de formato como emails, URLs, etc.
       * 
       * En este caso:
       * - Probamos diferentes formatos válidos de email
       * - Cada string en @ValueSource se pasa como parámetro 'validEmail'
       * - El test se ejecuta 4 veces, una por cada email
       */

      // Act: Set the email and validate it
      user.setEmail(validEmail);

      // Assert: All provided emails should be considered valid
      assertThat(user.isValidEmail()).isTrue();
    }

    @ParameterizedTest
    @DisplayName("Should invalidate invalid emails")
    @ValueSource(strings = {
        "invalid-email",
        "@example.com",
        "user@",
        "user.com",
        ""
    })
    void shouldInvalidateInvalidEmails(String invalidEmail) {
      user.setEmail(invalidEmail);
      assertThat(user.isValidEmail()).isFalse();
    }

    @Test
    @DisplayName("Should handle null email validation")
    void shouldHandleNullEmailValidation() {
      user.setEmail(null);
      assertThat(user.isValidEmail()).isFalse();
    }
  }

  @Nested
  @DisplayName("Getters and Setters Tests")
  class GettersSettersTests {

    @Test
    @DisplayName("Should set and get ID correctly")
    void shouldSetAndGetId() {
      /*
       * EXPLICACIÓN DE ESTA PRUEBA:
       * ===========================
       * 
       * ¿Qué está probando esta prueba?
       * Esta prueba verifica que los métodos setter y getter para el campo 'id'
       * funcionan correctamente. Con Lombok @Data, estos métodos se generan
       * automáticamente, pero es importante probar que funcionen como se espera.
       * 
       * ¿Por qué es importante?
       * - Los getters y setters son fundamentales para el encapsulamiento
       * - Con Lombok, verificamos que la generación automática funciona
       * - El ID es un campo crítico para la identificación de entidades
       * - Prueba la integridad de los datos al ser almacenados y recuperados
       * 
       * Patrón de Testing: Arrange-Act-Assert
       * - Arrange: Preparamos el valor esperado (123L)
       * - Act: Llamamos setId() y luego getId()
       * - Assert: Verificamos que el valor recuperado sea igual al asignado
       */

      // Arrange: Prepare the expected ID value
      Long expectedId = 123L;

      // Act: Set the ID and retrieve it
      user.setId(expectedId);

      // Assert: Verify the retrieved value matches what was set
      assertThat(user.getId()).isEqualTo(expectedId);
    }

    @Test
    @DisplayName("Should set and get username correctly")
    void shouldSetAndGetUsername() {
      /*
       * EXPLICACIÓN DE ESTA PRUEBA:
       * ===========================
       * 
       * ¿Qué está probando esta prueba?
       * Verifica que el getter y setter del campo 'username' funcionen correctamente.
       * El username es un campo importante para la identificación del usuario.
       * 
       * ¿Por qué es importante?
       * - El username es la forma principal de identificar usuarios en el sistema
       * - Debe poder ser modificado y recuperado sin pérdida de datos
       * - Con Lombok @Data, verificamos la correcta generación de métodos
       * 
       * Estrategia de Testing:
       * - Usamos un valor distinto al valor por defecto
       * - Verificamos que no hay corrupción de datos en el proceso
       */

      // Arrange: Prepare a new username value
      String expectedUsername = "new_username";

      // Act: Set and get the username
      user.setUsername(expectedUsername);

      // Assert: Verify the value was stored and retrieved correctly
      assertThat(user.getUsername()).isEqualTo(expectedUsername);
    }

    @Test
    @DisplayName("Should set and get email correctly")
    void shouldSetAndGetEmail() {
      /*
       * EXPLICACIÓN DE ESTA PRUEBA:
       * ===========================
       * 
       * ¿Qué está probando esta prueba?
       * Verifica que el getter y setter del campo 'email' funcionen correctamente.
       * El email es crucial para la comunicación y autenticación del usuario.
       * 
       * ¿Por qué es importante?
       * - El email es usado para notificaciones y recuperación de contraseña
       * - Debe mantener su integridad durante las operaciones de lectura/escritura
       * - Es un campo que frecuentemente se actualiza en aplicaciones reales
       * 
       * Nota de Testing:
       * - Usamos un email válido para la prueba
       * - Esta prueba se enfoca en la funcionalidad básica get/set
       * - La validación de formato de email se prueba por separado
       */

      // Arrange: Prepare a valid email address
      String expectedEmail = "new@example.com";

      // Act: Set the email and retrieve it
      user.setEmail(expectedEmail);

      // Assert: Verify the email was stored correctly
      assertThat(user.getEmail()).isEqualTo(expectedEmail);
    }

    @Test
    @DisplayName("Should set and get createdAt correctly")
    void shouldSetAndGetCreatedAt() {
      /*
       * EXPLICACIÓN: Prueba los métodos get/set para el timestamp de creación.
       * El campo createdAt es crítico para auditoría y ordenamiento temporal.
       * Verificamos que las fechas se manejen correctamente sin pérdida de precisión.
       */

      // Arrange: Create a specific date/time for testing
      LocalDateTime expectedDateTime = LocalDateTime.of(2023, 1, 1, 12, 0);

      // Act & Assert: Set and verify the timestamp
      user.setCreatedAt(expectedDateTime);
      assertThat(user.getCreatedAt()).isEqualTo(expectedDateTime);
    }

    @Test
    @DisplayName("Should set and get active status correctly")
    void shouldSetAndGetActiveStatus() {
      /*
       * EXPLICACIÓN: Prueba los métodos para el estado activo/inactivo del usuario.
       * Este campo controla si el usuario puede acceder al sistema.
       * Probamos ambos estados (true/false) para verificar la funcionalidad completa.
       */

      // Act & Assert: Test setting to false
      user.setActive(false);
      assertThat(user.isActive()).isFalse();

      // Act & Assert: Test setting to true
      user.setActive(true);
      assertThat(user.isActive()).isTrue();
    }
  }

  @Nested
  @DisplayName("Object Contract Tests")
  class ObjectContractTests {

    @Test
    @DisplayName("Should implement equals correctly")
    void shouldImplementEqualsCorrectly() {
      Cliente user1 = TestDataFactory.createUserWithId(1L, "john", "john@example.com");
      Cliente user2 = TestDataFactory.createUserWithId(1L, "john", "john@example.com");
      Cliente user3 = TestDataFactory.createUserWithId(2L, "jane", "jane@example.com");

      // Reflexive
      assertThat(user1).isEqualTo(user1);

      // Symmetric
      assertThat(user1).isEqualTo(user2);
      assertThat(user2).isEqualTo(user1);

      // Different objects
      assertThat(user1).isNotEqualTo(user3);
      assertThat(user1).isNotEqualTo(null);
      assertThat(user1).isNotEqualTo("string");
    }

    @Test
    @DisplayName("Should implement hashCode correctly")
    void shouldImplementHashCodeCorrectly() {
      Cliente user1 = TestDataFactory.createUserWithId(1L, "john", "john@example.com");
      Cliente user2 = TestDataFactory.createUserWithId(1L, "john", "john@example.com");

      assertThat(user1.hashCode()).isEqualTo(user2.hashCode());
    }

    @Test
    @DisplayName("Should implement toString correctly")
    void shouldImplementToStringCorrectly() {
      // Act: Get the string representation (generated by Lombok @Data)
      Cliente testUser = TestDataFactory.createUserWithId(1L, "john", "john@example.com");
      String toString = testUser.toString();

      // Assert: Verify toString format generated by Lombok
      // Lombok @Data generates toString in format: ClassName(field1=value1,
      // field2=value2, ...)
      assertThat(toString)
          .contains("User(") // Lombok uses parentheses, not curly braces
          .contains("id=1")
          .contains("username=john")
          .contains("email=john@example.com")
          .contains("active=true");
    }
  }

  @Nested
  @DisplayName("Edge Cases Tests")
  class EdgeCasesTests {

    @Test
    @DisplayName("Should handle null values gracefully")
    void shouldHandleNullValues() {
      assertDoesNotThrow(() -> {
        user.setId(null);
        user.setUsername(null);
        user.setEmail(null);
        user.setCreatedAt(null);
      });
    }

    @Test
    @DisplayName("Should handle empty strings")
    void shouldHandleEmptyStrings() {
      assertDoesNotThrow(() -> {
        user.setUsername("");
        user.setEmail("");
      });
    }

    @Test
    @DisplayName("Should handle very long strings")
    void shouldHandleVeryLongStrings() {
      String longString = "a".repeat(1000);

      assertDoesNotThrow(() -> {
        user.setUsername(longString);
        user.setEmail(longString + "@example.com");
      });
    }
  }

  @Test
  @DisplayName("Should demonstrate TestDataFactory usage")
  void shouldDemonstrateTestDataFactoryUsage() {
    // Using factory methods
    Cliente basicUser = TestDataFactory.createBasicUser();
    assertThat(basicUser.getUsername()).isEqualTo("testuser");

    Cliente customUser = TestDataFactory.createUser("custom", "custom@example.com");
    assertThat(customUser.getUsername()).isEqualTo("custom");

    Cliente userWithId = TestDataFactory.createUserWithId(5L, "test", "test@example.com");
    assertThat(userWithId.getId()).isEqualTo(5L);

    Cliente inactiveUser = TestDataFactory.createInactiveUser();
    assertThat(inactiveUser.isActive()).isFalse();

    // Using builder pattern
    Cliente builtUser = TestDataFactory.aUser()
        .withId(10L)
        .withUsername("builder_user")
        .withEmail("builder@example.com")
        .inactive()
        .build();

    assertThat(builtUser.getId()).isEqualTo(10L);
    assertThat(builtUser.getUsername()).isEqualTo("builder_user");
    assertThat(builtUser.isActive()).isFalse();
  }
}